import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import Form from '../components/Form';
import NavBar from '../components/NavBar';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [displayForm, setDisplayForm] = useState(false);
  let vidRef: React.RefObject<HTMLVideoElement> = React.createRef();
  
  const onVideoEnd = () => {
    setDisplayForm(true);
    if(vidRef.current) {
      vidRef.current.className += ' tranisition-blur delay-100 transition-opacity-60 blur-sm ease-out'
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <video className="w-full h-full fixed inset-0 -z-10 grayscale" ref={vidRef} id="background-video" autoPlay muted onEnded={onVideoEnd}>
          <source src='/marvelintroTrimmed.mp4' type='video/mp4'/>
        </video>
        {
          displayForm ?  <Form />: null
        }
      </main>
      {/* <Client /> */}
    </div>
  )
}
